[package]
name = "soltools"
version = "0.1.0"
authors = ["Evan Maddock <maddock.evan@vivaldi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"
git2 = "0.13"
glob = "0.3.0"
sudo = "0.6.0"
